steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'pusercf2'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'EngSrvCloud_vvq4vz3c2fhvyk1n'
      space: 'dev'